GET http://localhost:3000/
Authorization: Bearer 1232d13

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ansrud45@gmail.com",
  "password": "test12"
}

### 이메일 인증
POST http://localhost:3000/auth/register/email
Content-Type: application/json

{
  "nickname": "닉네임123",
  "email": "ansrud1003@naver.com"
}

### 회원가입
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "ansrud45@gmail.com",
  "password": "test12",
  "nickname": "닉네임",
  "authCode": 8635
}

### 프로젝트 목록
GET http://localhost:3000/projects

### 프로젝트 생성
POST http://localhost:3000/projects
Content-Type: application/json

{
  "email": "ansrud45@gmail.com",
  "title": "Show Me The Money",
  "description": "test desc",
  "stack": ["vanilla JS", "node.js"],
  "members": ["A", "B", "C", "D"]
}

### 프로젝트 읽기
GET http://localhost:3000/projects/LTLAQpxQzcMx6Zl1uF1TB

### 프로젝트 수정
PUT http://localhost:3000/projects/pD7i4ZH1SmW70S5kjwYWF
Content-Type: application/json

{
  "title": "Show Me The Money!!!",
  "description": "test desc",
  "stack": ["vanilla JS", "node.js"],
  "members": ["A", "B", "C", "D"],
  "image": " "
}

### 프로젝트 삭제
DELETE http://localhost:3000/projects/p43OxDMyjS2sc2twf2zCV

### 댓글 읽기
GET http://localhost:3000/comments/pD7i4ZH1SmW70S5kjwYWF

### 댓글 작성
POST http://localhost:3000/comments/rPhfm4ZIg79UXpy3h0l07
Content-Type: application/json

{
  "email": "ansrud45@gmail.com",
  "content": "test!!!!",
  "rating": 5
}

### 댓글 수정
PUT http://localhost:3000/comments/Q-QxzkK90ucRz19xGvB5x
Content-Type: application/json

{
  "content": "제발",
  "rating": 1
}

### 댓글 삭제
DELETE http://localhost:3000/comments/Q-QxzkK90ucRz19xGvB5x

### 인증코드 확인
POST http://localhost:3000/auth/code-check
Content-Type: application/json

{
  "code": 7998,
  "email": "ansrud41232135@gmail.com"
}