GET http://localhost:3000/

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Kyle@naver.com",
  "password": "112123124"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Kyle"
}

###

GET http://localhost:3000/comments/VHbYyvkOC7pAAOsxl06XT

###

POST http://localhost:3000/comments/VHbYyvkOC7pAAOsxl06XT
Content-Type: application/json

{
  "email": "ansrud45@gmail.com",
  "content": "test",
  "rating": 5
}

###
POST http://localhost:3000/auth/register/email
Content-Type: application/json

{
  "nickname": "닉네임",
  "email": "ansrud1003@naver.com"
}